#!/bin/bash
#
# keepalive.sh - Oracle Always Free instance keepalive (systemd-backed, single file)
# Usage: sudo ./keepalive.sh install | start | stop | enable | disable | status | uninstall
#
# "install" writes out the worker logic and a systemd unit, then enables it
# at boot so it survives reboots (including a daily scheduled one).
# "start"/"stop" wrap systemctl for temporary pauses when you want the box
# free for real work. "disable" keeps it off through reboots too.

SERVICE_NAME="keepalive"
INSTALL_DIR="/opt/keepalive"
WORKER_DST="${INSTALL_DIR}/keepalive-worker.sh"
UNIT_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

require_root() {
    if [ "$EUID" -ne 0 ]; then
        echo "Run this with sudo: sudo $0 $1"
        exit 1
    fi
}

ensure_stress_ng() {
    if command -v stress-ng >/dev/null 2>&1; then
        echo "stress-ng already installed."
        return
    fi

    echo "stress-ng not found. This is what actually generates the CPU load, so it's needed."
    read -rp "Install it now via apt? [Y/n]: " reply
    reply=${reply:-Y}

    if [[ "$reply" =~ ^[Yy]$ ]]; then
        apt update -qq && apt install -y stress-ng
        if command -v stress-ng >/dev/null 2>&1; then
            echo "stress-ng installed successfully."
        else
            echo "Install seemed to fail. The service will fall back to a plain bash CPU loop instead, which still works, just less clean."
        fi
    else
        echo "Skipping. The service will fall back to a plain bash CPU loop instead, which still works, just less clean."
    fi
}

install() {
    require_root install

    ensure_stress_ng

    mkdir -p "$INSTALL_DIR"

    cat > "$WORKER_DST" <<'WORKER_EOF'
#!/bin/bash
#
# Auto-generated by keepalive.sh install. Runs the actual burst loop.

CPU_BURST_SECONDS=300      # how long each CPU burst lasts
INTERVAL_HOURS=4           # how often it runs
PING_URL="https://1.1.1.1" # lightweight network touch

while true; do
    echo "$(date): starting burst"

    if command -v stress-ng >/dev/null 2>&1; then
        stress-ng --cpu 1 --timeout "${CPU_BURST_SECONDS}s"
    else
        timeout "${CPU_BURST_SECONDS}" bash -c 'while true; do :; done'
    fi

    curl -s -o /dev/null "$PING_URL"

    echo "$(date): burst done, sleeping ${INTERVAL_HOURS}h"
    sleep "${INTERVAL_HOURS}h"
done
WORKER_EOF

    chmod +x "$WORKER_DST"

    cat > "$UNIT_FILE" <<EOF
[Unit]
Description=Oracle instance keepalive
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/bin/bash ${WORKER_DST}
Restart=always
RestartSec=30
StandardOutput=append:/var/log/keepalive.log
StandardError=append:/var/log/keepalive.log

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME"
    systemctl start "$SERVICE_NAME"

    echo "Installed and enabled. Will auto-start on every boot, including scheduled reboots."
    echo "Logs at /var/log/keepalive.log"
}

start() {
    require_root start
    systemctl start "$SERVICE_NAME"
    echo "Started."
}

stop() {
    require_root stop
    systemctl stop "$SERVICE_NAME"
    echo "Stopped. Note: it's still enabled, so it WILL restart automatically on next reboot."
    echo "Use '$0 disable' if you want it to stay off through a reboot too."
}

disable() {
    require_root disable
    systemctl stop "$SERVICE_NAME" 2>/dev/null
    systemctl disable "$SERVICE_NAME"
    echo "Stopped and disabled. Won't come back until you run '$0 start' or '$0 enable'."
}

enable() {
    require_root enable
    systemctl enable "$SERVICE_NAME"
    systemctl start "$SERVICE_NAME"
    echo "Re-enabled and started."
}

status() {
    echo -n "Summary: "
    quick_status
    echo
    systemctl status "$SERVICE_NAME" --no-pager
    echo
    echo "Last 10 log lines:"
    tail -n 10 /var/log/keepalive.log 2>/dev/null
}

uninstall() {
    require_root uninstall
    systemctl stop "$SERVICE_NAME" 2>/dev/null
    systemctl disable "$SERVICE_NAME" 2>/dev/null
    rm -f "$UNIT_FILE"
    rm -rf "$INSTALL_DIR"
    systemctl daemon-reload
    echo "Fully removed."

    if command -v stress-ng >/dev/null 2>&1; then
        echo
        read -rp "Also remove stress-ng? It won't be used by anything else unless you know otherwise. [y/N]: " reply
        if [[ "$reply" =~ ^[Yy]$ ]]; then
            apt remove -y stress-ng
            echo "stress-ng removed."
        else
            echo "Leaving stress-ng installed."
        fi
    fi
}

quick_status() {
    if ! systemctl list-unit-files "${SERVICE_NAME}.service" >/dev/null 2>&1 || \
       [ -z "$(systemctl list-unit-files "${SERVICE_NAME}.service" 2>/dev/null)" ]; then
        echo "Not installed yet"
        return
    fi

    local active enabled
    active=$(systemctl is-active "$SERVICE_NAME" 2>/dev/null)
    enabled=$(systemctl is-enabled "$SERVICE_NAME" 2>/dev/null)

    if [ "$active" = "active" ]; then
        echo -n "Running"
    else
        echo -n "Stopped"
    fi

    if [ "$enabled" = "enabled" ]; then
        echo " (survives reboot)"
    else
        echo " (will NOT survive reboot)"
    fi
}

pause() {
    echo
    read -rp "Press Enter to continue..." _
}

menu() {
    while true; do
        clear
        echo "=================================="
        echo "   Oracle Keepalive Control Menu"
        echo "=================================="
        echo -n "Status: "
        quick_status
        echo "=================================="
        echo "1) Install (first-time setup)"
        echo "2) Start"
        echo "3) Stop (pauses now, resumes on next reboot)"
        echo "4) Enable (resume + survive reboots)"
        echo "5) Disable (stop + stay off through reboots)"
        echo "6) Status"
        echo "7) Uninstall (remove completely)"
        echo "8) Check/install stress-ng"
        echo "9) Exit"
        echo "=================================="
        read -rp "Choose an option [1-9]: " choice
        echo

        case "$choice" in
            1) install; pause ;;
            2) start; pause ;;
            3) stop; pause ;;
            4) enable; pause ;;
            5) disable; pause ;;
            6) status; pause ;;
            7) uninstall; pause ;;
            8) ensure_stress_ng; pause ;;
            9) echo "Bye."; exit 0 ;;
            *) echo "Not a valid option, pick 1-9."; pause ;;
        esac
    done
}

case "$1" in
    install)   install ;;
    start)     start ;;
    stop)      stop ;;
    enable)    enable ;;
    disable)   disable ;;
    status)    status ;;
    uninstall) uninstall ;;
    "")        menu ;;
    *) echo "Usage: $0 {install|start|stop|enable|disable|status|uninstall}" ;;
esac
